# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: MicrosoftCorporation.VisualFoxProODBCDriver
PackageVersion: 1.0.0
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: msi
  InstallerUrl: http://www.topol.eu/files/download/other/VFPODBC.msi
  InstallerSha256: D90311F554DAB6DFDF3DE576FFBD948F7DAA154FDB937C5AEA9291FF4DC2AECC
  ProductCode: '{31821EFE-1B31-4744-9FB0-208F92BD7168}'
ManifestType: installer
ManifestVersion: 1.1.0

